apiVersion: apps/v1
kind: Deployment
metadata:
  name: v-nodeapp-deployment
  labels:
    app: v-nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v-nodeapp
    template:
      metadata:
        labels:
          app: v-nodeapp
      spec:
        containers:
        - name: nodeserver
          image: vinhngo/v-nodeapp:latest
          ports:
          - containers: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: v-nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
